### ISSUE TITLE
Sorry, your user account was not successfuly authenticated. Reason [MAPFAIL|BUILTINNOTSET]

### ISSUE THREAD

**Issue by Jarvil** [PlaneteStream/moodle-tinymce_planetestream#1]
Hello,

When I Try to use planet estream button from TinyMCE or ATTO i get an error message;

"Sorry

Sorry, your user account was not successfuly authenticated. Reason [MAPFAIL|BUILTINNOTSET]"

What does it mean?

I'm using Moodle 3.1 and tinymce_planetestream 6.20 and atto_planetestream 6.20

**Comment by PlaneteStream** [comment]
Hi Jarvil,

In your Planet eStream administration console, under the plugin options page, you should be able to enable/disable user mapping and also set a default user. User mapping will attempt to match a Moodle username to a Planet eStream username for authentication within the plugin. The default user will be used if user mapping is disabled or fails.

It looks like your Planet eStream user name does not match your Moodle user name. You will have to set a default built-in user or create a new built-in eStream account in order to use the plugin.

**Comment by Jarvil** [comment]
Hello,

Thanks for the quick reply.
